# -*- coding: utf-8 -*-
"""Yes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epy-AgV7rTNDD0RSTJOvULnRUWbCPsp8
"""

import tkinter as tk
from tkinter import messagebox
import pickle
import os

# Entity classes definitions
class Employee:
    def __init__(self, employee_id, name, department, job_title, basic_salary, age, date_of_birth, passport_details):
        self.employee_id = int(employee_id)
        self.name = name
        self.department = department
        self.job_title = job_title
        self.basic_salary = basic_salary
        self.age = age
        self.date_of_birth = date_of_birth
        self.passport_details = passport_details

class Event:
    def __init__(self, event_id, event_type, theme, date, time, duration, venue_id, client_id, budget):
        self.event_id = int(event_id)
        self.event_type = event_type
        self.theme = theme
        self.date = date
        self.time = time
        self.duration = duration
        self.venue_id = venue_id
        self.client_id = client_id
        self.budget = budget

class Client:
    def __init__(self, client_id, name, contact_details, address, budget):
        self.client_id = int(client_id)
        self.name = name
        self.contact_details = contact_details
        self.address = address
        self.budget = budget

class Guest:
    def __init__(self, guest_id, name, contact_details, address, special_requirements, event_id):
        self.guest_id = int(guest_id)
        self.name = name
        self.contact_details = contact_details
        self.address = address
        self.special_requirements = special_requirements
        self.event_id = event_id

class Supplier:
    def __init__(self, supplier_id, name, service_type, contact_details, address):
        self.supplier_id = int(supplier_id)
        self.name = name
        self.service_type = service_type
        self.contact_details = contact_details
        self.address = address

class Venue:
    def __init__(self, venue_id, name, address, capacity, booking_status):
        self.venue_id = int(venue_id)
        self.name = name
        self.address = address
        self.capacity = capacity
        self.booking_status = booking_status

# GUI class for event management system
class EventManagementSystemGUI:
    def __init__(self, master):
        self.master = master
        self.master.title("Event Management System")
        self.entities = {
            'employee': [], 'event': [], 'client': [], 'guest': [], 'supplier': [], 'venue': []
        }
        self.create_widgets()
        self.load_data()

    def create_widgets(self):
        buttons = ['Add', 'Delete', 'Modify', 'Display']
        for index, name in enumerate(buttons):
            button = tk.Button(self.master, text=name, command=getattr(self, f"{name.lower()}_entity"))
            button.grid(row=0, column=index, padx=10, pady=5)

    def add_entity(self):
        entity_type = self.ask_entity_type()
        if entity_type in self.entities:
            entity_class = globals()[entity_type.capitalize()]
            entity_details = self.get_entity_details(entity_class)
            entity = entity_class(*entity_details)
            self.entities[entity_type].append(entity)
            self.save_data()
            messagebox.showinfo("Success", f"{entity_type.capitalize()} added successfully!")
        else:
            messagebox.showerror("Error", "Invalid entity type!")

    def delete_entity(self):
        entity_type = self.ask_entity_type()
        if entity_type in self.entities:
            entity_id = int(input(f"Enter ID of the {entity_type} to delete: "))
            initial_count = len(self.entities[entity_type])
            self.entities[entity_type] = [e for e in self.entities[entity_type] if getattr(e, entity_type + '_id') != entity_id]
            if len(self.entities[entity_type]) < initial_count:
                self.save_data()
                messagebox.showinfo("Success", f"{entity_type.capitalize()} deleted successfully!")
            else:
                messagebox.showerror("Error", f"{entity_type.capitalize()} not found!")

    def modify_entity(self):
        entity_type = self.ask_entity_type()
        if entity_type in self.entities:
            entity_id = int(input(f"Enter ID of the {entity_type} to modify: "))
            entity = next((e for e in self.entities[entity_type] if getattr(e, entity_type + '_id') == entity_id), None)
            if entity:
                for key, value in vars(entity).items():
                    new_val = input(f"Enter new {key} (current: {value}): ")
                    setattr(entity, key, new_val if new_val else value)
                # Update the ID attribute
                entity_id_new = int(input(f"Enter new ID for the {entity_type} (current: {entity_id}): "))
                setattr(entity, entity_type + '_id', entity_id_new)
                self.save_data()
                messagebox.showinfo("Success", f"{entity_type.capitalize()} modified successfully!")
            else:
                messagebox.showerror("Error", f"{entity_type.capitalize()} not found!")

    def display_entity(self):
        entity_type = self.ask_entity_type()
        if entity_type in self.entities:
            entity_id = int(input(f"Enter ID of the {entity_type} to display: "))
            entity = next((e for e in self.entities[entity_type] if getattr(e, entity_type + '_id') == entity_id), None)
            if entity:
                details = '\n'.join([f"{key}: {value}" for key, value in vars(entity).items()])
                messagebox.showinfo(f"{entity_type.capitalize()} Details", details)
            else:
                messagebox.showerror("Error", f"{entity_type.capitalize()} not found!")

    def get_entity_details(self, entity_class):
        return [input(f"Enter {arg}: ") for arg in entity_class.__init__.__code__.co_varnames[1:]]

    def ask_entity_type(self):
        types = ', '.join([key for key in self.entities.keys()])
        entity_type = input(f"Enter entity type ({types}): ")
        return entity_type.lower()

    def load_data(self):
        for entity_type in self.entities:
            filename = f"{entity_type}.pkl"
            if os.path.exists(filename):
                with open(filename, "rb") as f:
                    self.entities[entity_type] = pickle.load(f)

    def save_data(self):
        for entity_type, data in self.entities.items():
            with open(f"{entity_type}.pkl", "wb") as f:
                pickle.dump(data, f)

    def run(self):
        self.master.mainloop()

def main():
    root = tk.Tk()
    app = EventManagementSystemGUI(root)
    app.run()

if __name__ == "__main__":
    main()